<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Thank you for confirming</title>
  <script>
    // Extract the 'redirectUrl' parameter from the URL
    const params = new URLSearchParams(window.location.search);
    const redirectUrl = params.get("redirectUrl");

    if (redirectUrl) {
      // Redirect to the specified URL
      window.location.href = redirectUrl;
    } else {
      // If no redirect URL is provided, show an error message
      document.body.innerHTML = "<h1>Error: No redirect URL specified.</h1>";
    }
  </script>
</head>
<body>
  <h1>Thank you for confirming</h1>
</body>
</html>
